export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const ADD_MULTIPLE_TO_WATCHLIST = "ADD_MULTIPLE_TO_WATCHLIST";
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
export const CLEAR_WATCHLIST = "CLEAR_WATCHLIST";
export const TOGGLE_WATCHLIST = "TOGGLE_WATCHLIST";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
